### ISSUE TITLE
Module not found: Can't resolve 'devlop'

### ISSUE THREAD

**Issue by ningshunqiang** [syntax-tree/mdast-util-frontmatter#1]
### Initial checklist

- [X] I read the [support docs](https://github.com/syntax-tree/.github/blob/main/support.md)
- [X] I read the [contributing guide](https://github.com/syntax-tree/.github/blob/main/contributing.md)
- [X] I agree to follow the [code of conduct](https://github.com/syntax-tree/.github/blob/main/code-of-conduct.md)
- [X] I searched [issues](https://github.com/search?q=user%3Asyntax-tree&type=issues) and [discussions](https://github.com/orgs/syntax-tree/discussions) and couldn’t find anything (or linked relevant results below)

### Affected package

"version": "2.0.1",

### Steps to reproduce

/node_modules/mdast-util-frontmatter/lib/index.js   Module not found: Can't resolve 'devlop'

### Actual behavior

/node_modules/mdast-util-frontmatter/lib/index.js   Module not found: Can't resolve 'devlop'

### Expected behavior

success

### Runtime

node@20.15.0

### Package manager

yarn@1.22.19

### Operating system

window10

### Build and bundle tools

webpack

**Comment by ChristianMurphy** [comment]
Welcome @ningshunqiang! 👋 
Devlop is a dependency https://github.com/syntax-tree/mdast-util-frontmatter/blob/d76616b88bdafdbbcd97247c4d3a8a41cc71ae48/package.json#L39
And is hosted on the registry
https://www.npmjs.com/package/devlop

Most likely you either:
1. Have an incomplete install, try clearing your node_modules folder and installing again
2. Have a misconfigured web pack config
